CREATE TABLE `vak` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `naam` VARCHAR(255) NOT NULL
);

CREATE TABLE `gebruiker` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `gebruikersnaam` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `niveau` VARCHAR(255),
  `leerjaar` VARCHAR(255),
  `school` VARCHAR(255),
  `vak_id` INT NOT NULL,
  FOREIGN KEY (`vak_id`) REFERENCES `vak`(`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE `onderwerp` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `naam` VARCHAR(255) NOT NULL,
  `vak_id` INT NOT NULL,
  FOREIGN KEY (`vak_id`) REFERENCES `vak`(`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE `quiz` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `titel` VARCHAR(255) NOT NULL,
  `onderwerp_id` INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`onderwerp_id`) REFERENCES `onderwerp`(`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
